### PR TITLE
Video Popup added to entry page

### PR DESCRIPTION
**Pull request by arorasomya**
- video popup button added to the map section
- video popup added to the bottom right
- popup customized for different screens

image

image

image

### CODE REVIEW

**Comment by theodormarcu** [comment]
Currently reviewing this.

**Comment by theodormarcu** [comment]
This is really great work! Approving this with some small changes:

* There should be better spacing between the button and the geocoder. Adding ```m-2``` or ```mb-2``` could be really helpful.
Screen Shot 2020-05-25 at 12 31 13

* I think the video should be a bit smaller on desktop. I couldn't follow the instructions in the video side-by-side otherwise.

I think the ```<div>```'s height should be small enough to fit between the map and the bottom of the screen. However, if this takes too much time we can include it in a future PR.

Screen Shot 2020-05-25 at 12 33 30

**Comment by arorasomya** [comment]
> This is really great work! Approving this with some small changes:
> 
> * There should be better spacing between the button and the geocoder. Adding `m-2` or `mb-2` could be really helpful.
> 
> Screen Shot 2020-05-25 at 12 31 13
> 
> * I think the video should be a bit smaller on desktop. I couldn't follow the instructions in the video side-by-side otherwise.
> 
> I think the `<div>`'s height should be small enough to fit between the map and the bottom of the screen. However, if this takes too much time we can include it in a future PR.
> 
> Screen Shot 2020-05-25 at 12 33 30

How does this look:
image

**Comment by theodormarcu** [comment]
I like it! I think it makes a big difference.

*Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )

**Pull request merged**
