### PR TITLE
new home page design

### PR DESCRIPTION
**Pull request by k-y-le**
**changes**
- updated home page based upon designs
- changed outline buttons and button radius based on design - more blue and more rounded, in general
- added new logo on home page
- updated container to be wider on home page

**to test**
- load up the home page
- check for typos

**screenshot**
image

### CODE REVIEW

**Comment by okusio** [comment]
Looks so good! Thanks for putting this together :) 
A few super duper minor changes:
- Put your community on the map font slightly smaller
- "Are you the leader of an organization" font slightly larger 
- "Partner with us" font slight smaller
- the circle logo after the green square slightly smaller

**Comment by k-y-le** [comment]
> Looks so good! Thanks for putting this together :)
> A few super duper minor changes:
> 
> * Put your community on the map font slightly smaller
> * "Are you the leader of an organization" font slightly larger
> * "Partner with us" font slight smaller
> * the circle logo after the green square slightly smaller

made these changes!
image

**Review by arorasomya — APPROVED** [review]
image

The changes look really nice! Was just curious if we want the font for "Select your state to get started" to look this big on mobile?

**Comment by okusio** [comment]
Definitely much smaller than that. I would say close to half the size.

**Comment by k-y-le** [comment]
Made that change and merging now !

**Pull request merged**
