### PR TITLE
Added Google Signup/Login/Connection/Deletion Ability

### PR DESCRIPTION
**Pull request by Chuk116**
**changes**
- Adds the ability to log in/signup using a Google account, and connect an existing account to a Google account

**test**
- On login, click "Login with Google" and choose a Google Account you have
- On an existing account, go to the Account Settings Page. You should be able to connect an account. If you click on the link to manage existing third-party connections, you should be taken to a page where you can remove connected third-party accounts or connect more.
- If you try to signup with a Google Account that has the same email as an account you've already created, you should be redirected to the Third Party Signup Error page.

**screenshots**
- login page with Google button
Screen Shot 2021-03-02 at 9 28 43 PM

- third-party signup error page
Screen Shot 2021-03-02 at 9 34 55 PM

- Account Settings Page
Screen Shot 2021-03-02 at 9 26 46 PM

- Manage Third-Party Connections Page
Screen Shot 2021-03-02 at 9 27 59 PM

### CODE REVIEW

**Comment by k-y-le** [comment]
Exciting! When I tried to test, I ran into an error when connecting my Google account to my existing acct. any idea where this error may be coming from?
image

**Comment by Chuk116** [comment]
> Exciting! When I tried to test, I ran into an error when connecting my Google account to my existing acct. any idea where this error may be coming from?
> image

Yea, I forgot to mention. You have to add the credentials for Google OAuth2 to the Social Application model. The credentials are in Bitwarden. I'll look into a way to automatically populate the field but if you know of how to do so please let me know

**Comment by okusio** [comment]
Can we make the button look more like this?

**Comment by k-y-le** [comment]
Got it working - looks really good! Had no issues with setting up my account and played around with it a bit with no issues. Two tiny notes:
the spacing is kinda off here, looks like there's a bit too much margin on the top of the button vs the bottom
image

also this screenshot is from an account that i already have connected to my google account -- is it possible/easy enough to make it so that if google is already connected, the button doesn't pop up and instead it just has the line on the bottom?

**Comment by Chuk116** [comment]
> Got it working - looks really good! Had no issues with setting up my account and played around with it a bit with no issues. Two tiny notes:
> the spacing is kinda off here, looks like there's a bit too much margin on the top of the button vs the bottom
> image
> 
> also this screenshot is from an account that i already have connected to my google account -- is it possible/easy enough to make it so that if google is already connected, the button doesn't pop up and instead it just has the line on the bottom?

I can fix the spacing. Regarding the second part of the comment, I can look into that for a follow-up PR. It is possible, however, to connect multiple social accounts at once so maybe it won't be so bad to leave it?

**Review by k-y-le — APPROVED** [review]
Awesome - changes look good, and I agree that it's no problem to leave the button there, for now.

**Pull request merged**
