### PR TITLE
Survey Frontend Redesign and Backend Fix

### PR DESCRIPTION
**Pull request by Chuk116**
**changes**
- Redesigns the frontend of the survey pages. 
- Adds error handling and navigation flow for the address page and the survey page

**screenshots**
  
*Address Page*
address-page-error\ 
  
*Survey Start Page*
survey-start-laptop
survey-start-mobile
survey-start-tablet\
  
*Survey P1 Page*
surveyp1-error
surveyp1-laptop
surveyp1-mobile
surveyp1-tablet\ 
  

*Comm Name Page*
comm-name-error
comm-name-laptop
comm-name-mobile
comm-name-tablet

### CODE REVIEW

**Comment by Chuk116** [comment]
Actually, I'm just going to merge the changes. Afterwards, feel free to mention any changes that need to happend

**Comment by okusio** [comment]
awesome :)
A few things
- can we make sure the text on the tell us about your community page is updated. Also, can we make sure that the line length for the examples is long enough so that there's never one word. 
- make sure the text for the survey page is updated
- add the examples to the name your community page

**Comment by okusio** [comment]
also can we make the text boxes on the survey page less wide (around the size of this GitHub text box)

**Comment by arorasomya** [comment]
image

image

**Pull request merged**
