### PR TITLE
Retroactive drive add

### PR DESCRIPTION
**Pull request by jasony123123**
enables a community to be added retroactively to a drive. 

A user may add a drive in the following conditions: user is logged in, viewing a community that doesn't have a drive, viewing a community they authored.

The drives that a user can add to are public, active drives in the same state as the community.

To test: 
1. create a community without a drive
2. once submitted retroactively add to a drive
3. confirm from drive dashboard that the community is added 
4. confirm that the community can not be added to anymore drives

### CODE REVIEW

**Review by k-y-le — COMMENTED** [review]
looks good! i didn't encounter any errors while testing. one small change : let's change up the design of this dropdown to be a bit more in touch with the rest of the design, @okusio thoughts?

image

**Comment by jasony123123** [comment]
mm ok ... how so?

**Comment by okusio** [comment]
This was the original design, but ill change it up to have a drop down. Version 2 is on its way

**Comment by jasony123123** [comment]
oops ignore that

**Pull request merged**
