### PR TITLE
Entry Page - Phone number validation - frontend and backend

### PR DESCRIPTION
**Pull request by arorasomya**
- Added phone number validation
- clean function added in the backend for the phone number field
- alert added on the form

image

image

### CODE REVIEW

**Comment by lauren-johnston** [comment]
I just checked this out locally and not seeing an error message when I tried to validate 1212131311222

**Comment by arorasomya** [comment]
> 1212131311222

image
i copied and pasted your number and it showed up on mine. Let me look into this.

**Comment by theodormarcu** [comment]
Currently reviewing this.

**Comment by arorasomya** [comment]
> It worked for me.
> 
> A few considerations:
> 
> * I think there's an argument for using the full-featured phone number field. For example, here you could simply add a phone number that goes 123-156-7890, which is wrong per the standard since the 156 part should never start that way (phone numbers also have to follow a certain number of considerations). I don' think this is necessary now, but it's something to keep in mind for the future.
> * Alerts should go under the field title (e.g. the Phone is invalid alert should go under the phone number title for the field). This can be resolved with #105 and #111

- that's a valid point -> although I'm not sure if the full featured one necessarily keeps track of the area codes. From what it looked like, it added functionality for International numbers. But I can look further into this and resolve in a subsequent pr!

**Comment by theodormarcu** [comment]
Great point! Definitely not a great priority rn.

*Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )

**Pull request merged**
