### PR TITLE
Re-organized Entry Form Sections

### LINKED ISSUE #104: Searching for location on entry page should automatically go to next step
**Describe the bug**
When searching for a starting location on the entry page, there isn't any signifier that the search went through without pressing next.

**To Reproduce**
1. Search for community (press enter)
2. nothing happens lol

**Expected behavior**
automatically go to map page

### PR DESCRIPTION
**Pull request by theodormarcu**
Resolves #104, #59, #73.

**Key Changes:**
- Entry form sections follow the pencil and paper form more closely (#73).
- Adds disclaimer that form is not submitted to commission and instructions (#59).
- Combines map and geocoder in one section to create an easier transition (#104).
- Moves map last so that users can build context before drawing.
- Updates map fields to make them more accessible.
- Added personal information disclaimer.

**How to test:**
1. Go to entry form.
2. Create an entry. Make sure JS works for section traversal ("Next", "Back", "Hide/Edit Section").
3. Fill form. 
4. Read text.
5. Check that map only toggles after you search for a location in the geocoder.

**To Do/Next Steps:**
1. Discuss content with PGP/VNP. Is our disclaimer clear enough?
2. Is our personal information disclaimer good enough?

**Screenshots:**

Screen Shot 2020-05-22 at 01 17 10
Screen Shot 2020-05-22 at 01 17 03
Screen Shot 2020-05-22 at 01 18 41

### CODE REVIEW

**Comment by theodormarcu** [comment]
Fixed the issues you mentioned. Now, if there's an error with the form, it will be displayed to the user if they try to submit it again. This replicates prior behavior.

Note that the form validation is still a bit janky. I will submit an issue that details what should happen. That will be a separate PR because it affects other things as well.

**Comment by theodormarcu** [comment]
That's a good catch. I'll add it to the issue I mentioned. Thank you!

**Comment by arorasomya** [comment]
Checked out and reviewed as well! 
@lauren-johnston to clarify the issue you flagged: the community that you drew is actually not bigger than half the state area of NJ, which is why it passes. That's the threshold we are checking against at the moment. I tried doing the same and once you drag the corners to make the community bigger and it surpasses that threshold, one of the vertices is automatically deleted for error handling purposes. Maybe this is an issue of changing that threshold?

**Comment by theodormarcu** [comment]
Oh thanks for checking that Somya! I thought the handlers were being called wrongly, but I'm glad to hear it's working as intended.

**Comment by arorasomya** [comment]
Also the other memory issue you mentioned, is something that I already made an issue for and it is on the backend - mapbox side. We really need to fix it for michigan since the communities will on average be on the larger side.

**Pull request merged**
