### PR TITLE
visualizations fully updated

### PR DESCRIPTION
**Pull request by k-y-le**
- Visualizations now include the other issues field, addresses (for those with permission to see them), and have been cleaned up a bit to look nicer

** to see **
go to any map page yee haw 🤠 

image
image

### CODE REVIEW

**Comment by theodormarcu** [comment]
Currently reviewing this.

**Comment by theodormarcu** [comment]
@k-y-le I'm trying to review this but I'm dealing with an odd error. The lines point to the mixpanel code, but I removed it on my local copy and I didn't get any results.

**Pages affected:**

* Organization Map Page
Screen Shot 2020-05-25 at 12 45 43
* Organization Review Page
Screen Shot 2020-05-25 at 12 45 38
* Campaign Map Page
Screen Shot 2020-05-25 at 12 45 51
* Campaign Review Page
Screen Shot 2020-05-25 at 12 45 57

**Comment by theodormarcu** [comment]
I did some digging and it seems that there is a problem with ```get_item```. More specifically, if the entry does not have an address associated with it, then the ```get_item``` template tag will not fail gracefully. I propose that this is addressed in this PR and you first check whether an entry has an address or not. It is possible that older entries will not have addresses.

Otherwise, I checked the visual updates and they are beautiful. I like how the address and name are displayed, although in the future we might have to consider making them more functional (but that's after we get more data!). I am such a big fan @k-y-le :)

**Comment by lauren-johnston** [comment]
> I did some digging and it seems that there is a problem with `get_item`. More specifically, if the entry does not have an address associated with it, then the `get_item` template tag will not fail gracefully. I propose that this is addressed in this PR and you first check whether an entry has an address or not. It is possible that older entries will not have addresses, which is why this should be addressed now.
> 
> Otherwise, I checked the visual updates and they are beautiful. I like how the address and name are displayed, although in the future we might have to consider making them more functional (but that's after we get more data!). I am such a big fan @k-y-le :)

Worth trying `get_object_or_404()`: https://docs.djangoproject.com/en/3.0/topics/http/shortcuts/#get-object-or-404

**Comment by theodormarcu** [comment]
Thanks for the suggestion! I think this might be appropriate in other instances as you want the page to still display the entry if it has no address associated with it. The problem isn't that the model raises a DoesNotExist exception (the model and queryset exist fine), but that the template expects that each community has an address associated with it and tries to show it. Thus, when an org admin/moderator looks at an older entry that does not have an address, Django attempts to get the address for it based on the entry id within the template, but that raises a Python KeyError.

*Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )

**Comment by lauren-johnston** [comment]
> Thanks for the suggestion! I think this might be appropriate in other instances as you want the page to still display the entry if it has no address associated with it. The problem isn't that the model raises a DoesNotExist exception (the model and queryset exist fine), but that the template expects that each community has an address associated with it and tries to show it. Thus, when an org admin/moderator looks at an older entry that does not have an address, Django attempts to get the address for it based on the entry id within the template, but that raises a Python KeyError.

Oh gotcha! Sorry I should've looked into this further before making the suggestion. In this case, it seems like doing a filter instead of a get would do the trick because that won't return an error. Then we can just check if the filter query returned an empty query set in which case we would not display anything.

**Comment by k-y-le** [comment]
> I did some digging and it seems that there is a problem with `get_item`. More specifically, if the entry does not have an address associated with it, then the `get_item` template tag will not fail gracefully. I propose that this is addressed in this PR and you first check whether an entry has an address or not. It is possible that older entries will not have addresses, which is why this should be addressed now.
> 
> Otherwise, I checked the visual updates and they are beautiful. I like how the address and name are displayed, although in the future we might have to consider making them more functional (but that's after we get more data!). I am such a big fan @k-y-le :)

hm so the logic in the template tags is to check whether or not an entry has a phone number. if so, then it displays the phone number and address -- I don't think it's possible for any entries to have a phone number but no address associated with it? since both are required in the current form and were not in the previous one, unless i'm missing something there

i can push a fix but it would involve making a new template tag i'm pretty sure and just want to make sure that's necessary

(also finding it hard to test because i don't have any old entries in my local db and there's a non-null constraint on the phone number field so i can't delete it)

**Comment by lauren-johnston** [comment]
> > I did some digging and it seems that there is a problem with `get_item`. More specifically, if the entry does not have an address associated with it, then the `get_item` template tag will not fail gracefully. I propose that this is addressed in this PR and you first check whether an entry has an address or not. It is possible that older entries will not have addresses, which is why this should be addressed now.
> > Otherwise, I checked the visual updates and they are beautiful. I like how the address and name are displayed, although in the future we might have to consider making them more functional (but that's after we get more data!). I am such a big fan @k-y-le :)
> 
> hm so the logic in the template tags is to check whether or not an entry has a phone number. if so, then it displays the phone number and address -- I don't think it's possible for any entries to have a phone number but no address associated with it? since both are required in the current form and were not in the previous one, unless i'm missing something there
> 
> i can push a fix but it would involve making a new template tag i'm pretty sure and just want to make sure that's necessary
> 
> (also finding it hard to test because i don't have any old entries in my local db and there's a non-null constraint on the phone number field so i can't delete it)

For flexibility (if we decide to make phone numbers optional for people not submitting to campaigns for example)  I think it would be helpful not to associate these two fields together.

**Comment by k-y-le** [comment]
> > > I did some digging and it seems that there is a problem with `get_item`. More specifically, if the entry does not have an address associated with it, then the `get_item` template tag will not fail gracefully. I propose that this is addressed in this PR and you first check whether an entry has an address or not. It is possible that older entries will not have addresses, which is why this should be addressed now.
> > > Otherwise, I checked the visual updates and they are beautiful. I like how the address and name are displayed, although in the future we might have to consider making them more functional (but that's after we get more data!). I am such a big fan @k-y-le :)
> > 
> > 
> > hm so the logic in the template tags is to check whether or not an entry has a phone number. if so, then it displays the phone number and address -- I don't think it's possible for any entries to have a phone number but no address associated with it? since both are required in the current form and were not in the previous one, unless i'm missing something there
> > i can push a fix but it would involve making a new template tag i'm pretty sure and just want to make sure that's necessary
> > (also finding it hard to test because i don't have any old entries in my local db and there's a non-null constraint on the phone number field so i can't delete it)
> 
> For flexibility (if we decide to make phone numbers optional for people not submitting to campaigns for example) I think it would be helpful not to associate these two fields together.

ok makes sense - i'll add the template tag and make the change

**Comment by k-y-le** [comment]
just committed that change @theodormarcu lmk if you're still getting the error

**Comment by theodormarcu** [comment]
Checking now!

**Comment by theodormarcu** [comment]
Works great for me. Thank you @k-y-le :) You're the best!
Screen Shot 2020-05-25 at 18 44 06

**Pull request merged**
