### PR TITLE
Content Changes 2

### LINKED ISSUE #186: Replace text on the user testing campaign page
**Is your feature request related to a problem? Please describe.**
Feedback from MI: "Please replace the current text on your User page with the text attached below". 

**Describe the solution you'd like**
Replace text on the user testing campaign page.

**Additional context:**
 See doc "June 5 User Test" attached to email from MI partner.

### LINKED ISSUE #187: Update lead text (“fair” → “impartial”) on the home page
**Is your feature request related to a problem? Please describe.**
Feedback: "Fair" is not a good word to use on our homepage.

**Describe the solution you'd like**
Change Home Page Lead Text (“Redistricting is coming …”) that mentions the word fair. Also change mention of fair in the "what is representable" paragraph.

### LINKED ISSUE #188: Remove phone number from form
**Is your feature request related to a problem? Please describe.**
Our partners would no longer like to include phone numbers in the form. "We have decided that phone numbers will present an unnecessary barrier". 

**Describe the solution you'd like**
Remove phone number in community_entry model and in form validation.

### LINKED ISSUE #190: Campaign page: Capitalize "Click Draw my community"
**Is your feature request related to a problem? Please describe.**
Bottom line of the User page says: "Click Draw my community", and it should say: "Click Draw My Community.” Capitalize all 3 words.

**Describe the solution you'd like**
Capitalize all 3 words.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by theodormarcu**
Close #186. Close #187. Close #188. Close #190.

- Updates content changes on front page and user testing page based on user feedback.
- Removes phone number.
- Makes Privacy and Terms links open in new tabs to avoid distraction.
- Updated Privacy Policy by adding edited text and removing information about getterms.
- Updated Terms by removing infomrtion about getterms.
Screen Shot 2020-06-06 at 09 47 25

### CODE REVIEW

**Comment by lauren-johnston** [comment]
Looks great--
Three comments:

1) We should probably remove the mention of fair on the "what is representable" section: 
(Sorry this was included in the text of this issue but wasn't very clear from the title https://github.com/Representable/representable/issues/187).

Screen Shot 2020-06-06 at 7 57 15 AM

2) They did not include this heading for "our submission period" in the doc for the campaign page so I think they want to leave the first heading out.

Screen Shot 2020-06-06 at 7 59 57 AM 

3) For the campaign page, the top half of the text should not be the default - the description of the campaign should still be loaded in. Now all campaigns are showing with this description for MI. at the top.

**Comment by theodormarcu** [comment]
Made requested changes. 

Privacy Section Without Campaign:
Screen Shot 2020-06-06 at 12 18 11


Privacy Section With Campaign:
Screen Shot 2020-06-06 at 12 34 52

Thanks Page:

(Campaign is called test)

Screen Shot 2020-06-06 at 12 33 52

**Comment by theodormarcu** [comment]
Resolves #189 (keeps some links, based on conversation).

**Comment by lauren-johnston** [comment]
One small thing spacing here is inconsistent:

Screen Shot 2020-06-06 at 9 43 10 AM

**Comment by theodormarcu** [comment]
Done! Sorry about that. 
Screen Shot 2020-06-06 at 12 52 30

**Pull request merged**
