### PR TITLE
Revert get calls to AWS

### PR DESCRIPTION
**Pull request by arorasomya**
Changes made:
* revert getting entries from aws for partner map/drive map/submission and review pages
* restored original geojson export functionality for submission/review/map pages

To test:
* create an entry in a drive
* view the map page for the drive
* view the partner map page for the org
* go to the review page and find ur entry
* export entries on the review page
* go to the submission page for the entry
* export the entry on the submission page
* go to the drive page and export entries
* go to org map page and export entries

### CODE REVIEW

**Review by k-y-le — COMMENTED** [review]
looks good to me! everything worked, except I noticed one thing

when exporting all maps as GeoJSON from the partner map page, it only exported the test community i just created, and not the other communities submitted to the same drive previously. not sure if that's a bug here or with the implementation of the multi-community export tho!

**Comment by arorasomya** [comment]
> looks good to me! everything worked, except I noticed one thing
> 
> when exporting all maps as GeoJSON from the partner map page, it only exported the test community i just created, and not the other communities submitted to the same drive previously. not sure if that's a bug here or with the implementation of the multi-community export tho!

Hmm interesting. Looking into it right now!

**Comment by arorasomya** [comment]
> > looks good to me! everything worked, except I noticed one thing
> > when exporting all maps as GeoJSON from the partner map page, it only exported the test community i just created, and not the other communities submitted to the same drive previously. not sure if that's a bug here or with the implementation of the multi-community export tho!
> 
> Hmm interesting. Looking into it right now!

Fixed!

**Review by k-y-le — APPROVED** [review]
change looks good!!!

**Pull request merged**
