### PR TITLE
added examples for the three interest fields

### PR DESCRIPTION
**Pull request by arorasomya**
- added an examples button (tooltip) that shows examples in line with the paper and pencil form
- will add it for other_considerations post consolidation of the fields in one section
image

image

image

### CODE REVIEW

**Comment by theodormarcu** [comment]
Reviewing this right now.

**Comment by theodormarcu** [comment]
There are some problems with the mobile version. You can debug them using the Chrome console and see device on mobile there.

Screen Shot 2020-05-23 at 11 05 18
Screen Shot 2020-05-23 at 11 05 07

**Comment by arorasomya** [comment]
So @lauren-johnston suggested doing a expandable/collapsable component that is triggered when u click on the link for the examples. Looks like this:
image
 but without the card header aspect. 
image
Would say "show examples" instead of "edit details"

**Comment by arorasomya** [comment]
Updates:
- changed show examples from a button to accordion style section expander
- added examples as placeholders in the inputs
image

**Pull request merged**
