### PR TITLE
update wording on entry pages

### PR DESCRIPTION
**Pull request by k-y-le**
changed wording to entry page to match designs
before survey
image
survey questions
image
image
mapping
image

### CODE REVIEW

**Comment by Chuk116** [comment]
Maybe there could be a little bit of margin between the questions and the examples in the dropdown. Outside of that, it looks good to me!

**Comment by okusio** [comment]
Agree on that. Also if we can increase the line length on the examples in
the community of interest explanation part. Also if we can switch black
text to the dark grey that would be great.

**Comment by k-y-le** [comment]
Thanks for the feedback! @Chuk116 @okusio I updated with more margin + gray text; I don't think increasing the line length is too feasible without it looking strange as the text goes beyond the boxes / mismatches with the other aspects of the page... but can make it work if we think it's necessary to increase the length !

image

**Comment by k-y-le** [comment]
oh @okusio did you mean on the page before the survey page? I made these changes
image

**Comment by Chuk116** [comment]
Looks great!

**Pull request merged**
