### PR TITLE
Content Changes

### PR DESCRIPTION
**Pull request by theodormarcu**
Updated changes based on conversations with our partners.

1. **Entry page** is updated per our internal conversation.
a. Added instructions to get started.
b. Changed "Personal Information" to "Identifying Information"
c. Clarified instructions for filing interests fields.
d. Removed "Recommended" tags.
e. Changed the order of interests fields.
d. Removed issues (front-end ONLY for now). Discuss during meeting.
e. Updated instructions for drawing community.
f. Changed "vertex" to "point" on front-end.
g. Added disclaimer about editing communities on entry page.
h. Renamed "Save Entry" to "Save Community".
2. Updated **Thanks Page**.
a. Added updated disclaimer.
b. Added "Send Feedback" button and section.

Screenshots:
Screen Shot 2020-06-02 at 15 13 40

Screen Shot 2020-06-02 at 15 15 02
Screen Shot 2020-06-02 at 15 15 11

Screen Shot 2020-06-02 at 15 14 50

Screen Shot 2020-06-02 at 15 13 11

### CODE REVIEW

**Comment by theodormarcu** [comment]
Thank you for the review! Right now I changed so that you need to add 1/4 of the questions (other takes the place of issues). So you could complete say other and still submit the form. I thought this was the best way because it was most flexible. Do you think this will be a problem?

I will add a separate issue for #2. Not sure if we can easily change that for now.

**Comment by lauren-johnston** [comment]
> Thank you for the review! Right now I changed so that you need to add 1/4 of the questions (other takes the place of issues). So you could complete say other and still submit the form. I thought this was the best way because it was most flexible. Do you think this will be a problem?

Sounds good!

> I will add a separate issue for #2. Not sure if we can easily change that for now.

Great! Agreed it seems out of scope.

**Comment by theodormarcu** [comment]
Closes #165.

**Comment by theodormarcu** [comment]
Closes #163.

**Pull request merged**
