### PR TITLE
Pre-release changes

### PR DESCRIPTION
**Pull request by theodormarcu**
- Re-added video tutorial with updated changes.
- Re-aded educational guide on front-page.
- Added Contact us section in the footer.
- Changed all emails to team@representable.org in the repository and website.
- Added dev/prod mixpanel token in settings.

### CODE REVIEW

**Comment by theodormarcu** [comment]
Video tutorial always came in first!

**Comment by theodormarcu** [comment]
What device did you try with? I tried iphone 5/6/X and others (Moto G4) and it worked.

Screen Shot 2020-06-13 at 15 58 04
Screen Shot 2020-06-13 at 15 57 44
Screen Shot 2020-06-13 at 15 57 35


Only iphone 5 looks a bit weird but it does not exceed device width.

**Comment by lauren-johnston** [comment]
Ok oops when I checked out the branch again I hadn't pulled these new changes. Looks fine now but in future would be good to keep these in separate PRs to maintain feature separation and make it easier to keep track of what's happening in which PR.

**Comment by theodormarcu** [comment]
Fair point! Merging now.

**Pull request merged**
