### PR TITLE
Allowlist flow

### PR DESCRIPTION
**Pull request by jessiejofielding**
**Changes:**

- add private field to Drive
- add private field to CommunityEntry
- update AllowList to have a Drive field
- make CommunityEntry privacy match Drive privacy
- redirect from Drive entry to page to generic entry page if user is not on private drive's allowlist
- change frontend to allowlist and allowlist flow:
  - move allowlist away from org home
  - call it an invite list
  - have it only on private drives
  - add a "manage invite list" page
  - add a list of members on Manage page
  - allow csv uploads to add to allowlist
  - add an "add" button to add a single email address to the allowlist
  - add a remove button to allow org admins to remove members from the invite list
- hide private communities from everyone who is not an admin of the org to which they belong
- add "Private" tag to drive home

**To test:**
- migrate
- runserver 
- create a drive, and update private to True in postico or however you prefer to access your database
- see that the drive page for that drive includes a "private" tag
- look at "Manage Invite List"
- upload a csv of emails and see that they show up under "Invitees" 
- add an email using the add textbox-and-button and see that it shows up under "Invitees"
- click on the trashcan and remove a member and see that that email no longer is under "Invitees"
- try entering the same email twice and see that it doesn't appear a second time
- submit a community at /entry/drive/<drive_slug> 
- view drive/org map as org admin, see the private community
- view drive/org map as not org admin, check that there are no private communities 

**To do:**
- send an email with link to Invitees on being added (I need help with the flow of this especially with verification)

### CODE REVIEW

**Comment by lauren-johnston** [comment]
This is awesome! I'm going to start with some frontend suggestions:

1) Change "for Test" to black in Image 1
2) Change form field height to same height as button or put button on new line in Image 1
3) Change the title to "Upload an Email List" for Image 2

Image 1
Screen Shot 2020-08-11 at 1 05 46 PM

Image 2
Screen Shot 2020-08-11 at 1 07 22 PM

**Comment by jessiejofielding** [comment]
> This is awesome! I'm going to start with some frontend suggestions:
> 
> 1. Change "for Test" to black in Image 1
> 2. Change form field height to same height as button or put button on new line in Image 1
> 3. Change the title to "Upload an Email List" for Image 2
> 
> Image 1
> Screen Shot 2020-08-11 at 1 05 46 PM
> 
> Image 2
> Screen Shot 2020-08-11 at 1 07 22 PM

Made these changes!

**Comment by ETedward** [comment]
Hey Jessie! Happy to review, have you committed the email changes we worked on today?

**Comment by jessiejofielding** [comment]
> Hey Jessie! Happy to review, have you committed the email changes we worked on today?

Hey Edward, they should be here now :)

**Comment by ETedward** [comment]
Awesome stuff!! sorry can you say again how to replicate the email sending ... create a drive, then add some email addresses to the list, and see if we get an email sent to the email addresses?

**Comment by jessiejofielding** [comment]
> Awesome stuff!! sorry can you say again how to replicate the email sending ... create a drive, then add some email addresses to the list, and see if we get an email sent to the email addresses?

Create a drive, open postico, change "private" to true, then add some emails to the invite list, see if an email shows up (in the terminal on local, I believe)

**Comment by ETedward** [comment]
Thanks so much Jessie! sorry for the delay, reviewing right now.

**Comment by ETedward** [comment]
How Jessie! This is awesome work! Super impressive and super useful to see that the allow-list flow working.
So I went to check the email sending with production settings; after adding an email, it works! here's a screenshot.
Screen Shot 2020-12-31 at 1 57 29 PM
I've also made very small edits to the email title and content, but feel free to use or ignore.

Before approving, I wanted to ask a question about importing an entire CSV list. 
Clicking the upload button in the following screen does not seem to do anything for me. Then when I submit without any CSV uploaded (because I can't) it brings me to a Server Error (500) page. I know I was supposed to check only the email sending, so lmk if this bug is not relevant to this PR.

Screen Shot 2020-12-31 at 1 59 04 PM

**Comment by arorasomya** [comment]
image

spacing is off for the 'View' Button

**Comment by arorasomya** [comment]
image
no state chosen for the map problem

**Comment by arorasomya** [comment]
@k-y-le 
image
do you think we shud have the 'private' flag only for entries created after the drive was made private? shud that private flag show next to the entry or near the drive name that is private? thoughts?

**Comment by arorasomya** [comment]
image
can add an 'empty' row for emails after just clicking on 'add' without adding an email

**Comment by arorasomya** [comment]
image
when editing a newly created drive

**Comment by k-y-le** [comment]
Made the View button change, i think that the private flag should show in the drive name -- something like 

> User Testing Drive (Private)

perhaps?

**Pull request merged**
