### PR TITLE
FAQ & Glossary pages

### PR DESCRIPTION
**Pull request by k-y-le**
**changes**
- added FAQ and glossary pages to site
- added new dropdown to navbar : "Learn More"
- changed navbar carets to font awesome style
- created models for FAQs and Glossary definitions
- enabled creation of FAQ and Glossary entries in django admin

**to test**
- python manage.py migrate
- python manage.py runserver
- go to django admin (http://127.0.0.1:8000/admin/)
- create multiple new objects for Frequently Asked Questions and Glossary Definitions
- check formatting and behavior on http://127.0.0.1:8000/faq/
- check formatting and behavior on http://127.0.0.1:8000/glossary/

**screenshots**
image
image

### CODE REVIEW

**Comment by k-y-le** [comment]
**Update:** changed up the models + FAQs a bit to reflect different categories - for community members and for organizations

image

**Comment by Chuk116** [comment]
On figma, the text for the questions on the FAQ seems to be slightly smaller than it correctly looks.

Also maybe @okusio can confirm, but the design on the glossary page seems to feature a very subtle, light blue background such that there is a difference between it and the white container where the words are featured.

**Comment by k-y-le** [comment]
> On figma, the text for the questions on the FAQ seems to be slightly smaller than it correctly looks.
> 
> Also maybe @okusio can confirm, but the design on the glossary page seems to feature a very subtle, light blue background such that there is a difference between it and the white container where the words are featured.

made this first change - unsure about the second part with the light blue/gray background - imo i prefer having a standard white background for the entire page, curious your thoughts olivia/chuk !

**Comment by okusio** [comment]
I liked the blueish background and white box with the text in it, to kind of give a scroll like appearance, but im not super attached to it tbh

**Comment by okusio** [comment]
also could we put a little more padding for the drop down text in the faqs

**Comment by k-y-le** [comment]
made these changes + made it more mobile compliant

**faq**
image
**faq mobile**
image

**glossary**
image

**Pull request merged**
