### PR TITLE
state name entry page bug fix

### PR DESCRIPTION
**Pull request by arorasomya**
Users can't access entry/* where * is a keyword that is not a state abbreviation

To test:
Go to entry/* where * is not a state abbrev and check if you are redirected to the state selection page

### CODE REVIEW

**Review by k-y-le — APPROVED** [review]
looks good!!

**Comment by jasony123123** [comment]
It seems like `/entry/tx/` also redirects to `/entry_state_selection/`

**Comment by arorasomya** [comment]
> It seems like `/entry/tx/` also redirects to `/entry_state_selection/`

OMG u right, the fix isn't complete! Making changes right now!

**Review by jasony123123 — APPROVED** [review]
looks good

**Pull request merged**
