### PR TITLE
Adds TOC/Privacy Checkbox at the end of the form.

### LINKED ISSUE #120: Add Privacy Opt-In At The End of The Form
**Is your feature request related to a problem? Please describe.**
Users might not be aware of the privacy implications of using Representable.org. Add a privacy checkbox at the end of the form in order to clarify the implications of using Representable.

**Describe the solution you'd like**
A checkbox at the end with a quick disclaimer. The checkbox should prevent form submission if people don't check it.

### PR DESCRIPTION
**Pull request by theodormarcu**
Closes #120.

- Adds a checkbox for TOC/Privacy at the end of the form.
- Changes color of "What comes next?" from yellow (warning) to blue (info).

Screen Shot 2020-05-24 at 02 14 36

### CODE REVIEW

**Comment by theodormarcu** [comment]
It seems that one TravisCI check failed because of postgres, which is unrelated to these changes. 
`0.16s$ psql -U postgres -c "create extension postgis;"
ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
The command "psql -U postgres -c "create extension postgis;"" failed and exited with 1 during .
Your build has been stopped.`

**Comment by lauren-johnston** [comment]
> It seems that one TravisCI check failed because of postgres, which is unrelated to these changes.
> `0.16s$ psql -U postgres -c "create extension postgis;" ERROR: could not access file "$libdir/postgis-2.4": No such file or directory The command "psql -U postgres -c "create extension postgis;"" failed and exited with 1 during . Your build has been stopped.`

I restarted the build - sometimes Travis CI fails to start Postgres but this seems to be random and not a config issue.

**Comment by theodormarcu** [comment]
I like all of these suggestions. Replying in line:

> I feel like the turquoise color is still a bit jarring and could be replaced by a card like the one below (probably without centering). 

I played with the normal section, but I don't think it attracts enough attention to what is a very important step. I can make it primary rather than turqoise though.

> Also, it feels like the TOC needs a section of its own because it's floating separately otherwise. Maybe some of the information from the earlier privacy disclaimer could be moved to the bottom?

> Also, instead of the visible privacy disclaimer in the PI section we could potentially do something like the show examples below where it's "why do you need this information?" and it expands if you click on the link. Just an idea.


This is a good suggestion. I'll implement it.

**Comment by theodormarcu** [comment]
Updated form with requested changes.

Privacy dropdown:
Screen Shot 2020-05-24 at 14 13 39

TOC Section + Blue Alert:
Screen Shot 2020-05-24 at 14 15 37

**Comment by theodormarcu** [comment]
> Approved! Changes look really good. The below links are still turquoise so they could
> be changed to the primary color but that's the only thing I noticed.
> Screen Shot 2020-05-24 at 11 57 37 AM

THank you! Will add that as a separate issue, since I think we discussed changing this sitewide?

Edit: Added issue #127

**Comment by lauren-johnston** [comment]
Also quick comment on this example: I still think we should not prescribe any action ("put cherry farmers together in one district") bc that could invalidate data. Also, would it be possible to make the example just "farmers"? I was confused with the "tart cherry" part (sorry I know this is very pedantic stuff). Screen Shot 2020-05-24 at 11 58 47 AM

**Comment by theodormarcu** [comment]
> Also quick comment on this example: I still think we should not prescribe any action ("put cherry farmers together in one district") bc that could invalidate data. Also, would it be possible to make the example just "farmers"? I was confused with the "tart cherry" part (sorry I know this is very pedantic stuff). Screen Shot 2020-05-24 at 11 58 47 AM

I wrote this on the initial change request on a separate PR: Also, with regard to the point of prescribing solutions, I think that's fine based on our conversations with our partners. This is especially because this bias is baked into your reason for coming to Representable.org. Also, after getting that list of issues from our partners, I realized that most of them sounded the same ("we want to be in district x or separate from people who do y"). I'm open to other recommendations though.

Furthermore, I think we should loop Aaron in with regard to data invalidation. I'm unclear why providing an example would invalidate the data. I'll remove the tart cherry, but that was our partner's direct example.

My main concern is that **not** providing an example is confusing, because what else can the commission help you with other than redistricting. Alas, I think we should discuss this on Wednesday and Tuesday + loop in Aaron.

**Comment by lauren-johnston** [comment]
> > Also quick comment on this example: I still think we should not prescribe any action ("put cherry farmers together in one district") bc that could invalidate data. Also, would it be possible to make the example just "farmers"? I was confused with the "tart cherry" part (sorry I know this is very pedantic stuff). Screen Shot 2020-05-24 at 11 58 47 AM
> 
> I wrote this on the initial change request on a separate PR: Also, with regard to the point of prescribing solutions, I think that's fine based on our conversations with our partners. This is especially because this bias is baked into your reason for coming to Representable.org. Also, after getting that list of issues from our partners, I realized that most of them sounded the same ("we want to be in district x or separate from people who do y"). I'm open to other recommendations though.
> 
> Furthermore, I think we should loop Aaron in with regard to data invalidation. I'm unclear why providing an example would invalidate the data. I'll remove the tart cherry, but that was our partner's direct example.
> 
> My main concern is that **not** providing an example is confusing, because what else can the commission help you with other than redistricting. Alas, I think we should discuss this on Wednesday and Tuesday + loop in Aaron.

Makes sense! Let's definitely discuss with Aaron + partners.

**Pull request merged**
