### PR TITLE
survey example community

### PR DESCRIPTION
**Pull request by k-y-le**
**changes**
- adds an example community button to the survey page -- leads to a modal with Kai's community

**screenshots**
mobile
image
tablet
image
desktop
image
4k
image

### CODE REVIEW

**Comment by aceaton** [comment]
uh haha
Screen Shot 2021-07-22 at 3 49 30 PM
kai's a little stretched here lol

**Comment by aceaton** [comment]
Screen Shot 2021-07-22 at 3 53 42 PM
also the phrasing of this one sentence is a little funny

**Comment by aceaton** [comment]
also the button for example community is really big, just like the font size and stuff seems a bit much to me? not a big problem though. Other than that this all looks good

**Comment by nshapiro23** [comment]
good catch Anna, just checked and it also happens for me on Safari...
looks great for me on Chrome/Opera GX though


also,  I personally think that the font/size of the button looks great. though this may sound weird but i actually do think that the spacing in between each letter in the button is a bit much. overall looks amazing though

**Review by aceaton — APPROVED** [review]
looks good to me

**Pull request merged**
