### PR TITLE
added vid to entry preview page

### PR DESCRIPTION
**Pull request by json1016**

### CODE REVIEW

**Review by Chuk116 — COMMENTED** [review]
Congrats on the first PR Justin! 

Just some things to keep in mind: 
1) For frontend changes, if possible, include screenshots to the PR description so it'll be easier to see what the change is.

2) Add reviewers so that one of us can be notified about the PR

3) When using ids, try to make them as descriptive as possible and make sure that what you need to be done can't be done using classes. For example, the padding-right and margin-left that you did could be done using Bootstrap utility classes "pr-3" and "mr-2". It just helps to keep the stylesheet more condensed and readable (it's pretty discombobulated right now lol)

**Comment by json1016** [comment]
Oh I thought it auto-notified one of you my bad, thanks!
Appreciate the tips, I'll get those fixes in.

**Comment by json1016** [comment]
image

**Review by Chuk116 — COMMENTED** [review]
There seems to be an issue with the jinja rendering of the text "is silencing communities around the country" based on the screenshot that you sent Maybe it is because of the return spaces before the closing "%}".

Also, I forgot to mention, but for frontend changes, it's ideal to include screenshots for like mobile and tablet views to ensure screen compatibility. And feel free to include me as a reviewer, but also @okusio to give the thumbs up for the design.

**Comment by json1016** [comment]
image

image

**Comment by okusio** [comment]
Is there anyway to put a different cover over the video, and when you click it, it begins the video? I think it looks a bit messy now w the text. If not, I can talk to Mikala about updating the first image of the video to something simpler. Maybe just a blue cover image, like this.

Additionally, can we put a bit more padding around the video (above and below) for the mobile and iPad versions.

**Comment by json1016** [comment]
image

image

**Comment by json1016** [comment]
There used to be a parameter which hid the title, but YouTube deprecated that in 2018. As far as I can tell the only workaround is to have a different thumbnail.

**Review by Chuk116 — APPROVED** [review]

**Comment by okusio** [comment]
Sad, I’ll talk to Mikala about the thumbnail

**Pull request merged**
