### PR TITLE
redirecting to initial link after signup

### PR DESCRIPTION
**Pull request by ETedward**
version where redirect to entry or campaign pages works when ACCOUNT_EMAIL_VERIFICATION is set to "optional"
tested a few cases: when user logins directly; when user logins unsuccessfully (ie. with wrong password) then logins; when user creates new account; when user creates new account unsuccessfully (ie. username already exists) then creates new account.

### CODE REVIEW

**Comment by lauren-johnston** [comment]
If it's helpful, these are the errors on the signup page that cause the redirect so you can try to replicate: 

Screen Shot 2020-06-25 at 7 30 19 PM

**Comment by ETedward** [comment]
1. For the redirect after a failed login and sign up, after some testing, it seems that AllAuth was able to automatically handle those redirects. Is that able to work for you locally? 
2. Yes! with the "optional" we can work on adding a warning / re-verify back into the flow after someone has submitted a community.

**Comment by theodormarcu** [comment]
I think that should be included in this PR. I know PRs are supposed to represent atomic changes, but this seems to be tightly coupled.

**Comment by lauren-johnston** [comment]
Closing this for now so we can change the "master" branch to "main".

**Pull request closed without merging**
