### PR TITLE
Submission page redesign

### PR DESCRIPTION
**Pull request by Chuk116**
**changes**
- Redesigns the submission page to be as seen on the figma design (**Note: Minor modifications were made with agreeance from Olivia**)
- Removes entry-copy.html as the entry page redesign is complete

**Test**
- submit an entry

**screenshots**

*Desktop*
submission-filter-desktop
submission-filterx2-desktop

*Ipad Pro*
submission-filter-ipadpro

*ipad*
submission-ipad

*mobile*
submission-filter-mobile
submission-mobile

### CODE REVIEW

**Comment by k-y-le** [comment]
looks really great! the mobile and tablet views are excellent too. a couple small notes:

looks like there's a bit of an alignment issue for the demographics here
image
for some reason the buttons don't have matching styles
image

**Comment by Chuk116** [comment]
> looks really great! the mobile and tablet views are excellent too. a couple small notes:
> 
> looks like there's a bit of an alignment issue for the demographics here
> image
> for some reason the buttons don't have matching styles
> image

Okay, I think I just figured out the inconsistent button styling issue. What device do you get the issue with the demographics button?

**Comment by k-y-le** [comment]
> Okay, I think I just figured out the inconsistent button styling issue. What device do you get the issue with the demographics button?

Sorry, I totally forgot to mention my device ! I'm on a macbook pro 13 inch, full screen

**Comment by Chuk116** [comment]
> > Okay, I think I just figured out the inconsistent button styling issue. What device do you get the issue with the demographics button?
> 
> Sorry, I totally forgot to mention my device ! I'm on a macbook pro 13 inch, full screen

Okay, no problem. I think I have pushed the changes. Let me know if there are any more issues.

**Comment by k-y-le** [comment]
awesome - looks good! i also pushed a small button fix but it all looks great to me

i'll branch off of this and fix the pdf export - since it's based on the html it's currently broken. i'll try to get that out by tomorrow

**Review by k-y-le — APPROVED** [review]
approving as per above ^^

**Comment by Chuk116** [comment]
> approving as per above ^^

Okay awesome! I'll merge right now. I hope that I didn't block you with the late response.

**Comment by okusio** [comment]
Looks really good! Sorry I didn’t see this before.

**Pull request merged**
